#! /usr/bin/env python

def configure(conf):
	pass

def build(bld):
	bld(rule='touch ${TGT}', target='bar.txt')


from waflib.Build import BuildContext, InstallContext, UninstallContext, CleanContext

class _build(BuildContext):
	def execute(self):
		ret = self.exec_command('make all')
		if ret:
			self.fatal('make returned %r' % ret)
		super(_build, self).execute()

class _clean(CleanContext):
	def execute(self):
		self.exec_command('make clean')
		super(_clean, self).execute()

class _install(InstallContext):
	def execute(self):
		ret = self.exec_command('make install')
		if ret:
			self.fatal('make install returned %r' % ret)
		super(_install, self).execute()

class _uninstall(UninstallContext):
	def execute(self):
		self.exec_command('make uninstall')
		super(_uninstall, self).execute()

