#! /usr/bin/env python

def configure(conf):
	conf.env.thecmd = 'all'

def build(bld):
	bld(rule='touch ${TGT}', target='bar.txt')


from waflib.Build import BuildContext, InstallContext, UninstallContext, CleanContext

class _build(BuildContext):
	def compile(self):
		ret = self.exec_command('make %s' % self.env.thecmd)
		if ret:
			self.fatal('make returned %r' % ret)
		super(_build, self).compile()

class _clean(CleanContext):
	def clean(self):
		self.exec_command('make clean')
		super(_clean, self).clean()

class _install(InstallContext):
	def compile(self):
		ret = self.exec_command('make install')
		if ret:
			self.fatal('make install returned %r' % ret)
		super(_install, self).compile()

class _uninstall(UninstallContext):
	def compile(self):
		self.exec_command('make uninstall')
		super(_uninstall, self).compile()

