#! /usr/bin/env python

def configure(conf):
	pass

def build(bld):
	pass


from waflib.Build import BuildContext, InstallContext, UninstallContext, CleanContext

class _build(BuildContext):
	def execute(self):
		ret = self.exec_command('make all')
		if ret:
			self.fatal('make returned %r' % ret)
		super(BuildContext, self).execute()

class _clean(CleanContext):
	def execute(self):
		self.exec_command('make clean')
		super(CleanContext, self).execute()

class _install(InstallContext):
	def execute(self):
		ret = self.exec_command('make install')
		if ret:
			self.fatal('make install returned %r' % ret)
		super(CleanContext, self).execute()

class _uninstall(UninstallContext):
	def execute(self):
		self.exec_command('make uninstall')
		super(CleanContext, self).execute()

