#! /usr/bin/env python

top = '.'
out = 'build'

def options(ctx):
	ctx.tool_options('dang', tooldir='.')

def configure(ctx):
	ctx.check_tool('dang', tooldir='.')

def build(ctx):
	print(ctx.env.DANG)

