#! /usr/bin/env python

bld(
	features     = 'cc cstlib',
	source       = 'test_staticlib.c',
	target       = 'my_static_lib')

bld(
	features     = 'cc cprogram',
	source       = 'main.c',
	target       = 'test_static_link',
	uselib_local = 'my_static_lib')

