#! /usr/bin/env python

top = '.'
out = 'build'

def options(opt):
	opt.tool_options('some_tool', tooldir='.')

def configure(conf):
	pass

def build(bld):
	bld(rule='touch ${TGT}', target='foo.txt', always=True)
	bld(rule='cp ${SRC} ${TGT}', source='foo.txt', target='bar.txt', always=True)

