#! /usr/bin/env python
# encoding: utf-8

class copy(Task):
	run_str = '${COPY} ${COPYFLAGS} ${SRC} ${TGT}'

def configure(ctx):
	ctx.env.COPY      = '/usr/bin/cp'
	ctx.env.COPYFLAGS = ['-f']

def build(ctx):
	tsk = copy(env=ctx.env)
	tsk.set_inputs(ctx.path.find_resource('wscript'))
	tsk.set_outputs(ctx.path.find_or_declare('b.out'))
	ctx.add_to_group(tsk)

