#! /usr/bin/env python
# encoding: utf-8

from waflib.Task import Task
class foo(Task):
	vars = ['COPYFLAGS']
	def run(self):
		print(self.env.COPYFLAGS)

def configure(ctx):
	pass

def build(ctx):
	tsk = foo(env=ctx.env)

