#! /usr/bin/env python

def options(ctx):
	ctx.tool_options('compiler_c')

def configure(ctx):
	ctx.check_tool('compiler_c')

def build(ctx):
	#ctx.add_subdirs('fakelibs objects transitivity')
	ctx.add_subdirs('transitivity')

