#! /usr/bin/env python

def options(ctx):
	ctx.tool_options('compiler_c')

def configure(ctx):
	ctx.check_tool('compiler_c')

def build(ctx):
	sub = ctx.add_subdirs
	sub('fakelibs')
	sub('objects')
	sub('order')
	sub('transitivity')
	sub('headers')
	#sub('cycle') # this must raise an error during the build

