#!/usr/bin/env python
# encoding: utf-8
# Jérôme Carretero, 2010 (zougloub)

import sys, os
from Utils import subprocess

"""
"""

top = '.'
out = 'build'

def options(opt):
	opt.load('daemon', tooldir=['../../playground/daemon/'])

def configure(cfg):
	cfg.find_program('dot', var='DOT')
	cfg.find_program('convert', var='CONVERT')
	cfg.load('daemon', tooldir=['../../playground/daemon/'])
	cfg.find_program("sphinx-build", var="SPHINX_BUILD")

def build(bld):

	for x in bld.path.ant_glob('*.dot'):
		tg = bld(rule='${DOT} -Teps -o${TGT} ${SRC}', source=x, target=x.change_ext('.eps'))
		tg = bld(rule='${CONVERT} -geometry 500x500  ${SRC} ${TGT}', source=tg.target, target=x.change_ext('.png'))

	bld.add_group()

	bld(
		rule   = "${SPHINX_BUILD} -b html -d %s . %s" % (os.path.join(out, "doctrees"), os.path.join(out, "html")),
		cwd    = bld.path.abspath(),
		source = bld.path.parent.parent.find_dir('waflib').ant_glob('**/*.py') + bld.path.ant_glob('*.rst'),
		target = bld.path.find_or_declare('html/index.html')
    )

