#!/usr/bin/env python
# encoding: utf-8
# Jérôme Carretero, 2010 (zougloub)

import sys, os
from Utils import subprocess

out = "build"

def configure(cfg):
	cfg.find_program("sphinx-build", var="SPHINX_BUILD")

def build(bld):
	bld(
 	 rule="${SPHINX_BUILD} -b html -d %s . %s" % (os.path.join(out, "doctrees"), os.path.join(out, "html")),
	 name="sphinx_html",
	 cwd = bld.path.abspath(),
	 always=True,
    )
