#!/bin/bash
# a simple script to ease the transition from vagrant to Docker
# to run with docker compose with docker-compose.yml and Dockerfile in the root of the project folder

[ ! -f docker-compose.yml ] && [ ! -f Dockerfile ] && echo "docker-compose.yml and Dockerfile missing, make sure you are in the root of the smith project."

OS=$(uname -sm)

case $1 in
        "validate" | "check" | "config")
                echo "Validating configuration"
                docker compose config
                ;;
        "debug" | "logs")
                echo "Launching build without parallel mode, without cache and with logs"
                docker build . -t smith:latest --no-cache --progress=plain 2>&1 | tee build.log
                ;;
        "up" | "start")
                echo "Building image, spinning up the container and provisionning"
                docker compose -p smith build --pull
                docker compose up -d --remove-orphans 
                ;;
        "provision")
                echo "No need to use provision any longer, use up instead"
                ;;
        "status" | "ps")
                echo "Showing container status"
                docker compose ps
                ;;
        "ssh" | "enter" | "exec" | "run")
                echo "Entering the container in interactive mode (type exit to get back)"
                if [[ "$OS" == *"MSYS_NT-10"* ]]; 
                        then winpty docker compose run --rm smith
                        else docker compose run --rm smith
                fi
                ;;
        "when" | "time")
                echo -e "ID              Creation date                   Status"
                docker container ls --format '{{.ID}}\t{{.CreatedAt}}\t{{.State}}\t{{.Status}}'
                ;;
        "stop" | "halt" | "destroy" | "down")
                echo "Stopping and removing the container"
                docker compose down
                ;;
        "clean" | "prune" | "purge")
                echo "Purging stale images / containers and the whole build cache"
                docker stop "$(docker ps -aq)"
                docker rm "$(docker ps -aq)"
                docker rmi -f smith
                docker system prune -a
                ;;
        *)
                echo "Anvil: 🦾 🏗  helper for running a dockerized smith"
                echo "Usage: expected a parameter (alias) like:"
                echo "  ./anvil up (start)"
                echo "  ./anvil ssh (enter) (exec) (run)"
                echo "  ./anvil status (ps)" 
                echo "  ./anvil stop (halt) (destroy) (down)"
                ;;
esac
