#!/bin/bash
# Just a small helper to develop smith locally.
# it will remove the older ~/bin/smith and create a new one from the current source.

echo "building smith"
addondir=`pwd`/smithlib
addons=`find $addondir ! -name \*.pyc -type f -print0 | perl -F'\000' -ane 'print join(",",@F)'`
./waf-light --make-waf --tools=$addons --prelude=$'\tfrom waflib.extras import wsiwaf\n' --nostrip
mv waf smith
echo "removing old smith cached files in ~/bin/.waf*"
rm -rf ~/bin/.waf*
echo "(re)creating the symbolic link in ~/bin/"
cd ~/bin
ln -sf ~/repos/smith/smith smith
