#! /usr/bin/env python

"""
Compile some files with -O2 and others with -O3
"""

def options(opt):
	opt.tool_options('compiler_c')

def configure(conf):
	conf.check_tool('compiler_c')

def build(bld):
	bld.objects(
		source   = 'test.c',
		ccflags  = '-O3',
		target   = 'my_objs')

	bld.program(
		source   = 'main.c',
		ccflags  = '-O2',
		target   = 'test_c_program',
		use      = 'my_objs')
