#! /usr/bin/env python

def options(ctx):
	ctx.tool_options('compiler_c')

def configure(ctx):
	ctx.check_tool('compiler_c')

def build(ctx):
	ctx.stlib(source='a.c', target='lib1')
	ctx.shlib(source='b.c', target='lib2')
	ctx(features='c', source='c.c', target='obj1')
	ctx.program(source='main.c', target='app', use='obj1 lib1 lib2')
