#!/usr/bin/env python

bld.env.LIB_Z = ["z"]

bld(
	 features = "c",
	 source   = "a.c",
	 target   = "a",
	 use      = "Z",
	)

"""
bld.program(
	 source="a-test.c",
	 target="a-test",
	 use="a",
	)
"""

bld(
	 features = "c",
	 source   = "b.c",
	 target   = "b",
	 use      = "a",
	)

bld.program(
	 source = "c.c",
	 target = "c",
	 use    = "b",
	)

