#! /usr/bin/env python

top = '.'
out = 'build'

def options(opt):
	opt.tool_options('compiler_c')

def configure(conf):
	conf.check_tool('compiler_c')

	conf.define('AAA', 1)
	assert(repr(conf.env.DEFINES) == "['AAA=1']")

	conf.undefine('AAA')
	assert(not conf.env.DEFINES)

def build(bld):
	pass

