#! /usr/bin/env python

from waflib.TaskGen import feature, before

@feature('special_test')
@before('process_source')
def my_special_test(self):
	self.bld(rule='touch ${TGT}', target='foo')
	self.bld(rule='cp ${SRC} ${TGT}', source='foo', target='bar')
	self.source = []

def configure(conf):
	conf.check_cc(features='special_test', msg='my test!')

