#! /usr/bin/env python

def options(opt):
	opt.tool_options('compiler_c')

def configure(conf):
	conf.check_tool('compiler_c')

def build(bld):
	bld(
		export_incdirs = '.',
		name           = 'common_includes')

	main = bld.program(
		source         = 'main.c',
		target         = 'some_app',
		use            = 'common_includes')

