#! /usr/bin/env python

def options(opt):
	opt.tool_options('compiler_c')

def configure(conf):
	conf.check_tool('compiler_c')

def build(bld):
	bld(
		includes        = '. src',
		export_includes = 'src',
		name            = 'top_includes')

	bld.stlib(
		source          = 'a.c',
		target          = 'shlib1',
		use             = 'top_includes')

	bld.program(
		source          = 'main.c',
		target          = 'app',
		use             = 'shlib1',
		)

