#! /usr/bin/env python

def options(opt):
	opt.pimp('compiler_c')

def configure(conf):
	conf.check_tool('compiler_c')

def build(bld):
	bld.program(
		source       = 'main.c',
		target       = 'appname',
		features     = ['more', 'features', 'here'],

		includes     = ['.'],
		defines      = ['LINUX=1', 'BIDULE'],

		lib          = ['m'],
		libpath      = ['/usr/lib64'],
		stlib        = ['dl'],
		stlibpath    = ['/usr/local/lib'],
		linkflags    = ['-g'],

		install_path = '${SOME_PATH}/bin',
		vnum         = '1.2.3',
		ccflags      = ['-O2', '-Wall'],
		cxxflags     = ['-O3'],
		rpath        = ['/opt/kde/lib']
	)

