#!/usr/bin/env python
# encoding: utf-8


top = '.'
out = 'build'


def options(opt):
    opt.load('pep8')


def configure(conf):
    # warning after this comment
    
    conf.load('pep8')


def build(bld):
    bld(source='wscript')
