#!/usr/bin/python

srcdir = "../../script-test/keyboards/thai"

kbd(source = srcdir + '/thaitis0_5.kmn',
    font = "../../script-test/fonts/thai/font-source/Norasi.ttf",
    fontname = "Norasi Minor")

