#!/usr/bin/python
# this is a smith configuration file 

# set the default output folders
out="results"
DOCDIR="documentation"
OUTDIR="installers"
ZIPDIR="releases"

APPNAME="Tai-KBD"
VERSION="0.1"


srcdir = "../../script-test/keyboards/thai"

kbd(source = srcdir + '/thaitis0_5.kmn',
    font = "../../script-test/fonts/thai/font-source/Norasi.ttf",
    fontname = "Norasi Minor")

