#! /usr/bin/env python

def configure(ctx):
	print(type(ctx))

def foo(ctx):
	print(type(ctx))

def bar(ctx):
	print(type(ctx))

from waflib.Context import Context

class one(Context):
	cmd = 'bar'

class two(Context):
	cmd = 'tak'
	fun = 'bar'

