.TH SMITH 1 "Oct 10, 2012"
.SH NAME
smith \- a Python-based build system for WSI components 
.SH SYNOPSIS
.B smith
.RI [ options ]
.SH DESCRIPTION
This manual page documents briefly the
.B smith
commands.
.PP
\fBsmith\fP is a Python-based framework for building, testing and maintaining WSI components like fonts and keyboards.
it is based on waf. 
.SH OPTIONS
.TP
configure
.TP
build
.TP
pdfs
.TP
clean
.TP
distclean
.TP
zip
.TP
exe
.PP
For details of the available options see the complete manual.
.SH AUTHOR
waf was written by Thomas Nagy <tnagy1024@gmail.com>.
.PP
smith was written by Martin Hosken <martin_hosken@sil.org>.
.PP
