#!/usr/bin/python

import os
from os.path import join

# import pdb; pdb.set_trace()
srcdir=join("..", "..", "script-test", "fonts", "thai")
TESTDIR = join(srcdir, 'tests')
TESTRESULTSDIR = 'tests'
APPNAME = 'norasi'
VERSION = 0.8
SRCDIST = 'full_sfd'
STANDARDS = 'standards'
DEBPKG = 'ttf-sil-norasi'
LICENSE = 'OFL.txt'
COPYRIGHT = "Copyright SIL International. All rights reserved."

for f in ('Norasi', 'Norasi-Bold') :
    font(target = f + '.ttf',
        source = join(srcdir, 'font-source', f + '.sfd'),
        opentype = internal(),
        ap = join(srcdir, 'font-source', f + '.xml'),
        graphite = gdl(join('font-source', f + '.gdl'), master = join(srcdir, 'font-source' , 'master.gdl')),
        license = ofl('norasi'),
        script = 'thai')
