#! /usr/bin/env python

top = '.'
out = 'build'

def configure(ctx):
	pass

def dosomething(ctx):
	print(ctx.path.abspath())
	print(ctx.root.abspath())
	print("root children %r" % (ctx.path.children))
