#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006-2010 (ita)

# the following two variables are used by the target "waf dist"
VERSION='0.0.1'
APPNAME='cc_test'

top = '.'

import waflib.Configure
waflib.Configure.autoconfig = True

def options(opt):
	opt.tool_options('compiler_cc')
	opt.tool_options('gnu_dirs')

def configure(conf):
	conf.check_tool('compiler_cc')
	conf.check_cc(fragment="""#include<stdio.h>\nint main(){fprintf(stderr, "mu"); printf("%d", 22);return 0;}\n""", execute=True, define_name='HAVE_MU')
	conf.write_config_header('config.h')


	# uffff
	conf.write_config_header('debug/config.h')
	conf.write_config_header('release/config.h')
	conf.env.cfg_files = ['config.h']

def build(bld):
	bld.recurse('program stlib shlib')



from waflib.Build import BuildContext
class buildall_ctx(BuildContext):
	cmd = fun = "buildall"

def buildall(ctx):

	# find a better way to have a loop
	class debug(BuildContext):
		variant = cmd = 'debug'
	class release(BuildContext):
		variant = cmd = 'release'

	import Utils
	class sub_build(Utils.threading.Thread):
		def run(self):
			bld = self.cls(top_dir=ctx.top_dir, out_dir=ctx.out_dir)
			bld.load()
			bld.load_envs()
			bld.recurse([bld.run_dir])
			bld.compile()

	for cls in [debug, release]:
		f = sub_build()
		f.cls = cls
		f.start()

