#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2011 (ita)

"""
rpath processing example
"""

VERSION='0.0.1'
APPNAME='cc_test'

top = '.'

def options(opt):
	opt.load('compiler_c')

def configure(conf):
	conf.load('compiler_c local_rpath')

def build(bld):
	bld.shlib(source='a.c', target='foo')
	bld.program(source='main.c', target='bar', use='foo')

