#! /usr/bin/env python

def options(opt):
	opt.imp('compiler_c')

def configure(conf):
	conf.check_tool('compiler_c')

def build(bld):
	bld.stlib(
		source   = 'test_staticlib.c',
		target   = 'mylib',
		name     = 'stlib1')

	bld.program(
		source   = 'main.c',
		target   = 'app',
		includes = '.',
		use      = ['stlib1'])
