#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2005, 2010 (ita)

VERSION='1.0.0'
APPNAME='tex_test'

top = '.'
out = 'build'

def configure(conf):
	conf.check_tool('tex')
	if not conf.env.PDFLATEX:
		conf.fatal('could not find the program pdflatex')

def build(bld):
	bld.add_subdirs('src')

