# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '3.0.9.dev0+g1db0a9ce.d20230406'
__version_tuple__ = version_tuple = (3, 0, 9, 'dev0', 'g1db0a9ce.d20230406')
