#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2005, 2010 (ita)

VERSION='0.0.1'
APPNAME='qt4_test'

top = '.'
out = 'build'

def options(opt):
	opt.imp('compiler_cxx qt4')

def configure(conf):
	conf.check_tool('compiler_cxx qt4')
	conf.env.append_value('CXXFLAGS', ['-g']) # test

def build(bld):
	bld(
		features = 'qt4 cxx cxxprogram',
		uselib   = 'QTCORE QTGUI QTOPENGL QTSVG',
		source   = 'window.cpp glwidget.cpp main.cpp textures.qrc aboutDialog.ui',
		target   = 'window',
		includes = 'test .',
		defines  = 'WAF=1', # test
		#langname = 'langs',
	)

