#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2005, 2010 (ita)

VERSION='0.0.1'
APPNAME='qt4_test'

top = '.'
out = 'build'

def options(opt):
	opt.load('compiler_cxx qt4')

def configure(conf):
	conf.load('compiler_cxx qt4')
	conf.env.append_value('CXXFLAGS', ['-g']) # test

def build(bld):
	bld(
		features = 'qt4 cxx cxxprogram',
		uselib   = 'QTCORE QTGUI QTOPENGL QTSVG',
		source   = 'main.cpp textures.qrc but.ui',
		target   = 'window',
		includes = '.',
		defines  = 'WAF=1', # test
		#lang     = bld.path.ant_glob('linguist/*.ts'),
		#update   = True, # whether to update the .ts files
		#langname = 'somefile',
	)

# use the following if you want to add the include paths automatically
"""
from waflib.TaskGen import feature, before, after
@feature('cxx')
@after('process_source')
@before('apply_incpaths')
def add_includes_paths(self):
    incs = set(self.to_list(getattr(self, 'includes', '')))
    for x in self.compiled_tasks:
        incs.add(x.inputs[0].parent.path_from(self.path))
    self.includes = list(incs)
"""
