#! /usr/bin/env python

bld.shlib(
	source = 'test_shlib.c',
	target = 'my_shared_lib',
	vnum   = '1.2.3',
	defs   = 'foo.def')

bld.program(
	source = 'main.c',
	target = 'test_shared_link',
	use    = 'my_shared_lib')

