#!/usr/bin/env python

"""
when linked, object files should bring the libraries (uselib) they refer to
"""

bld.env.LIB_Z = ['z']

bld.objects(
	 source   = 'a.c',
	 target   = 'AA',
	 use      = 'Z',
	)

bld.objects(
	 source   = 'b.c',
	 target   = 'BB',
	 use      = 'A',
	 includes = '.',
	)

bld.program(
	 source = 'c.c',
	 target = 'CC',
	 use    = 'BB',
	)


