#!/usr/bin/env python

"""
objects can bring other objects to a final link
"""

bld.env.LIB_Z = ['z']

bld.objects(
		source   = 'a.c',
		target   = 'AA',
		use      = 'Z',
	)

bld.objects(
		source   = 'b.c',
		target   = 'BB',
		use      = 'AA',
		includes = '.',
	)

bld.program(
		source = 'c.c',
		target = 'CC',
		use    = 'BB',
	)

