#!/bin/bash
# shellcheck shell=sh disable=SC2046
# a simple script to fix WSL's executable bit limitations

echo "Fixing the execute bit in the current git local copy"

chmod -c u+x $(git ls-files --stage | grep -e "^100755" | cut -f2)
