# silfonts profile for fontspector

# Included profiles
include_profiles = [
"googlefonts",
"opentype",
"universal"
]

# Excluded checks
exclude_checks = [
"caps_vertically_centered",
"cjk_chws_feature",
"cjk_not_enough_glyphs",
"cmap/format_12",
"color_cpal_brightness",
"empty_glyph_on_gid1_for_colrv0",
"family/win_ascent_and_descent",
"fontdata_namecheck",
"fvar_name_entries",
"googlefonts/article/images",
"googlefonts/axes_match",
"googlefonts/axisregistry/fvar_axis_defaults",
"googlefonts/cjk_vertical_metrics",
"googlefonts/colorfont_tables",
"googlefonts/description/broken_links",
"googlefonts/description/eol_linebreaks",
"googlefonts/description/family_update",
"googlefonts/description/git_url",
"googlefonts/description/has_article",
"googlefonts/description/has_unsupported_elements",
"googlefonts/description/min_length",
"googlefonts/description/urls",
"googlefonts/description/valid_html",
"googlefonts/family/has_license",
"googlefonts/font_copyright",
"googlefonts/glyph_coverage",
"googlefonts/license/OFL_body_text",
"googlefonts/license/OFL_copyright",
"googlefonts/meta/script_lang_tags",
"googlefonts/metadata/axisregistry_bounds",
"googlefonts/metadata/unreachable_subsetting",
"googlefonts/repo/dirname_matches_nameid_1",
"soft_hyphen",
"typographic_family_name"
]

# Sections
[sections]
"Opentype Specification Checks" = [
]
"Universal Profile Checks" = [
]
"Font File Checks" = [
]
"Name table Checks" =  [
]
"Shaping Checks" =  [
]
"Outline Checks" =  [
]
"Googlefonts Checks" = [
]

# Overrides
[overrides]
[[overrides.alt_caron]]
code = "decomposed-outline"
status = "PASS"
reason = "some SIL fonts intentionally use decomposed outlines for Lcaron, dcaron, lcaron and tcaron."

[[overrides.legacy_accents]]
code = "legacy-accent-components"
status = "PASS"
reason = "SIL disagrees with the premise of this check."

[[overrides."opentype/family_naming_recommendations"]]
code = "bad-entries"
status = "WARN"
reason = "change from INFO to WARN so it shows up in our build results."

[[overrides.whitespace_glyphs]]
code = "missing-whitespace-glyph-0x00A0"
status = "WARN"
reason = "this is not as severe as assessed in the original check for 0x00A0."

[[overrides.contour_count]]
code = "contour-count"
status = "INFO"
reason = "SIL trusts designers, is concerned only with 'no-contour' results"

[[overrides.unwanted_tables]]
code = "unwanted-tables"
status = "WARN"
reason = "It's fine to have a fontTools Debg table in your font when developing since it's very useful for debugging, just make sure it gets removed when making a release"

# Configuration defaults
[configuration_defaults.file_size]
WARN_SIZE = 1048576
FAIL_SIZE = 9437184
