# silfonts profile for fontspector

# Included profiles
include_profiles = [
"googlefonts",
"opentype",
"universal"
]

# Excluded checks
exclude_checks = [
"caps_vertically_centered",
"cjk_chws_feature",
"cjk_not_enough_glyphs",
"cmap/format_12",
"color_cpal_brightness",
"empty_glyph_on_gid1_for_colrv0",
"family/uniqueness_first_31_characters",
"family/win_ascent_and_descent",
"fontdata_namecheck",
"fvar_name_entries",
"googlefonts/article/images",
"googlefonts/axes_match",
"googlefonts/axisregistry/fvar_axis_defaults",
"googlefonts/cjk_vertical_metrics",
"googlefonts/colorfont_tables",
"googlefonts/description/broken_links",
"googlefonts/description/eof_linebreaks",
"googlefonts/description/family_update",
"googlefonts/description/git_url",
"googlefonts/description/has_article",
"googlefonts/description/has_unsupported_elements",
"googlefonts/description/min_length",
"googlefonts/description/urls",
"googlefonts/description/valid_html",
"googlefonts/family/has_license",
"googlefonts/font_copyright",
"googlefonts/glyph_coverage",
"googlefonts/license/OFL_body_text",
"googlefonts/license/OFL_copyright",
"googlefonts/metadata/axisregistry_bounds",
"googlefonts/metadata/axisregistry_valid_tags",
"googlefonts/metadata/broken_links",
"googlefonts/metadata/canonical_style_names",
"googlefonts/metadata/canonical_weight_value",
"googlefonts/metadata/can_render_samples",
"googlefonts/metadata/category",
"googlefonts/metadata/category_hints",
"googlefonts/metadata/consistent_axis_enumeration",
"googlefonts/metadata/consistent_repo_urls",
"googlefonts/metadata/copyright",
"googlefonts/metadata/date_added",
"googlefonts/metadata/designer_profiles",
"googlefonts/metadata/designer_values",
"googlefonts/metadata/empty_designer",
"googlefonts/metadata/escaped_strings",
"googlefonts/metadata/family_and_full_names", 
"googlefonts/metadata/family_directory_name",
"googlefonts/metadata/familyname",
"googlefonts/metadata/filenames", 
"googlefonts/metadata/has_regular",
"googlefonts/metadata/includes_production_subsets",
"googlefonts/metadata/license",
"googlefonts/metadata/match_filename_postscript",
"googlefonts/metadata/match_fullname_postscript", 
"googlefonts/metadata/match_name_familyname", 
"googlefonts/metadata/match_weight_postscript", 
"googlefonts/metadata/menu_and_latin", 
"googlefonts/metadata/minisite_url",
"googlefonts/metadata/nameid/font_name", 
"googlefonts/metadata/nameid/post_script_name", 
"googlefonts/metadata/parses",
"googlefonts/metadata/primary_script",
"googlefonts/metadata/regular_is_400",
"googlefonts/metadata/reserved_font_name",
"googlefonts/metadata/single_cjk_subset",
"googlefonts/metadata/subset_order",
"googlefonts/metadata/undeclared_fonts",
"googlefonts/metadata/unique_full_name_values",
"googlefonts/metadata/unique_weight_style_pairs",
"googlefonts/metadata/unreachable_subsetting",
"googlefonts/metadata/valid_filename_values",
"googlefonts/metadata/valid_full_name_values",
"googlefonts/metadata/valid_post_script_name_values",
"googlefonts/metadata/weightclass",
"googlefonts/meta/script_lang_tags",
"googlefonts/name/license", 
"googlefonts/name/license_url",
"googlefonts/name/line_breaks",
"googlefonts/name/rfn", 
"googlefonts/name/version_format", 
"googlefonts/old_ttfautohint",
"googlefonts/repo/dirname_matches_nameid_1",
"googlefonts/repo/fb_report",
"googlefonts/repo/sample_image",
"googlefonts/repo/upstream_yaml_has_required_fields",
"googlefonts/repo/vf_has_static_fonts",
"googlefonts/repo/zip_files", 
"googlefonts/STAT/axis_order", 
"googlefonts/STAT/axisregistry", 
"googlefonts/STAT/compulsory_axis_values", 
"googlefonts/unitsperem",
"googlefonts/varfont/generate_static",
"googlefonts/varfont/has_HVAR",
"googlefonts/version_bump",
"inconsistencies_between_fvar_STAT",
"iso15008/intercharacter_spacing",
"iso15008/interline_spacing",
"iso15008/interword_spacing",
"iso15008/proportions",
"iso15008/stem_width",
"mandatory_avar_table",
"math_signs_width", 
"opentype/cff2_call_depth",
"opentype/cff_ascii_strings",
"opentype/cff_call_depth",
"opentype/cff_deprecated_operators",
"opentype/fvar/axis_ranges_correct",
"opentype/fvar/regular_coords_correct",
"opentype/name/postscript_vs_cff",
"opentype/slant_direction",
"opentype/STAT/ital_axis",
"opentype/varfont/distinct_instance_records",
"opentype/varfont/foundry_defined_tag_name",
"opentype/varfont/same_size_instance_records",
"opentype/varfont/stat_axis_record_for_each_axis",
"opentype/varfont/valid_default_instance_nameids",
"opentype/varfont/valid_nameids",
"opentype/weight_class_fvar",
"rupee",
"shaping/collides",
"shaping/forbidden",
"shaping/regression",
"soft_hyphen",
"STAT_in_statics", 
"STAT_strings",
"superfamily/list",
"superfamily/vertical_metrics",
"typographic_family_name",
"varfont/bold_wght_coord",
"varfont/consistent_axes",
"varfont/duplexed_axis_reflow",
"varfont/duplicate_instance_names",
"varfont/instances_in_order", 
"varfont/unsupported_axes"
]

# Sections
[sections]
"Opentype Specification Checks" = [
]
"Universal Profile Checks" = [
]
"Font File Checks" = [
]
"Name table Checks" =  [
]
"Shaping Checks" =  [
]
"Outline Checks" =  [
]
"Googlefonts Checks" = [
]

# Overrides
[overrides]
[[overrides.alt_caron]]
code = "decomposed-outline"
status = "PASS"
reason = "some SIL fonts intentionally use decomposed outlines for Lcaron, dcaron, lcaron and tcaron."

[[overrides.legacy_accents]]
code = "legacy-accent-components"
status = "PASS"
reason = "SIL disagrees with the premise of this check."

[[overrides."opentype/family_naming_recommendations"]]
code = "bad-entries"
status = "WARN"
reason = "change from INFO to WARN so it shows up in our build results."

[[overrides.whitespace_glyphs]]
code = "missing-whitespace-glyph-0x00A0"
status = "WARN"
reason = "this is not as severe as assessed in the original check for 0x00A0."

[[overrides.contour_count]]
code = "contour-count"
status = "INFO"
reason = "SIL trusts designers, is concerned only with 'no-contour' results"

[[overrides.unwanted_tables]]
code = "unwanted-tables"
status = "WARN"
reason = "It's fine to have a fontTools Debg table in your font when developing since it's very useful for debugging, just make sure it gets removed when making a release"

[[overrides."googlefonts/font_names"]]
code = "bad-names"
status = "WARN"
reason = "Regular is sometimes omitted from the PostScript name"

# Configuration defaults
[configuration_defaults.file_size]
WARN_SIZE = 1048576
FAIL_SIZE = 9437184
