#!/usr/bin/env python

bld.env.LIB_Z = ['z']

bld.objects(
	 source   = 'a.c',
	 target   = 'A',
	 use      = 'Z',
	)


bld.program(
	 source  = 'a-test.c',
	 target  = 'a-test',
	 use     = 'A',
	)

"""
bld(
	 features = "c",
	 source   = "b.c",
	 target   = "b",
	 use      = "a",
	)

bld.program(
	 source = "c.c",
	 target = "c",
	 use    = "b",
	)
"""

