#! /usr/bin/env python

top = '.'
out = 'bin'

def configure(conf):
	pass

def build(bld):
	tg = bld(source='test.pc.in')
	tg.env.VERSION = '1.0'
	tg.env.LIBS = 'moo'
	tg.env.XPM_LIBS = '-lxpm'
	tg.env.LIBICONV = '-liconv'
	tg.env.XPM_CFLAGS = '-O3'
