#! /usr/bin/env python
# encoding: utf-8

bld(
	features = 'cxx cxxprogram test',
	source   = 'HelloWorldTest.cpp',
	target   = 'unit_test_program',
	uselib   = 'CPPUNIT',
	uselib_local = 'unittestmain useless',
)

