APPNAME = 'norasi'
VERSION = '0.0.1'
prjbase = '../../script-test/'
fontbase = prjbase + 'fonts/thai/font-source/'
rmoverlap = prjbase + 'bin/rmOverlap'

for ext in ('', '-Bold') :
    fbase = 'Loma' + ext
    font(target = fbase + '.ttf',
         source = process(fontbase + fbase + '.sfd', cmd('../' + rmoverlap + ' ${DEP} ${TGT}')))
