#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2010 (ita)

VERSION='0.0.1'
APPNAME='cc_test'

top = '.'
out = 'build'

def options(opt):
	opt.load('compiler_c')

def configure(conf):
	conf.setenv('debug')
	conf.load('compiler_c')
	conf.env.CCFLAGS = ['-g']

	conf.setenv('release')
	conf.load('compiler_c')
	conf.env.CCFLAGS = ['-O2']

def build(bld):
	if bld.variant == 'debug':
		bld.env = bld.env_of_name('debug')
	elif bld.variant == 'release':
		bld.env = bld.env_of_name('release')
	else:
		bld.fatal('call "waf debug" or "waf release", and try "waf --help"')
	bld.program(source='main.c', target='app', includes='.')

from waflib import Build
for x in 'debug release'.split():
	class cls_build(Build.BuildContext):
		cmd = x
		variant = x

	class cls_clean(Build.CleanContext):
		cmd = 'clean_'+x
		variant = x

	class cls_install(Build.InstallContext):
		cmd = 'install_' + x
		variant = x

	class cls_uninstall(Build.UninstallContext):
		cmd = 'uninstall_' + x
		variant = x

