#! /usr/bin/env python

def configure(ctx):
    ctx.load('java')

def build(bld):

    bld(features  = 'javac seq',
        srcdir    = 'src',
        compat    = '1.5',
        use       = 'animals',
        name      = 'cats-src',
		seq_start = True
    )

    bld(features  = 'jar seq',
        basedir   = 'src',
        destfile  = 'cats.jar',
        name      = 'cats'
    )




