#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006-2010 (ita)

VERSION = '0.0.4'
APPNAME = 'java_test'

top = '.'
out = 'build'

def options(opt):
	opt.load('junit', tooldir='.')

def configure(conf):
	conf.load('java')

	try:
		ret = conf.load('junit', tooldir='.')
		conf.env.DO_JUNIT = True
	except:
		pass

	conf.check_java_class('java.io.FileOutputStream')
	conf.check_java_class('FakeClass')

def build(bld):

	# srcdir: directory containing the sources to compile
	# compat: java compatibility version number (compiling with a too recent jdk may cause problems)

	# basedir: directory containing the .class files to package
	# destfile: the destination file

	bld(features   = 'javac jar',
		srcdir     = 'src/main/java',
		outdir     = 'src',
		compat     = '1.5',
		sourcepath = ['src', 'sup'],

		basedir    = 'src',
		destfile   = 'foo.jar'
		)

	#jaropts = '-C default/src/ .', # can be used to give files
	#classpath = '..:.', # can be used to set a custom classpath
	#)

	bld.recurse('animals cats')

