#! /usr/bin/env python

top = '.'
out = 'build'

def options(opt):
	opt.load('dang', tooldir='.')

def configure(conf):
	conf.load('dang', tooldir='.')

def build(bld):
	bld.load('dang', tooldir='.')
