#! /usr/bin/env python

def options(opt):
	opt.tool_options('compiler_c')

def configure(conf):
	conf.check_tool('compiler_c')

def build(bld):
	bld.shlib(
		source   = 'a.c',
		target   = 'lib1')

	bld.stlib(
		source   = 'b.c',
		use      = 'cshlib',
		target   = 'lib2')

	bld.shlib(
		source   = 'c.c',
		target   = 'lib3',
		use      = 'lib1 lib2')

	bld.program(
		source   = 'main.c',
		target   = 'app',
		use      = 'lib3')

