#! /usr/bin/env python

top = '.'
out = 'build'

def configure(ctx):
    ctx.env['CXXFLAGS'] = ['-O2']
    ctx.env.store('test.txt')
    ctx.env.TEST        = 'test'

    new_env = ctx.env.__class__()
    new_env.load('test.txt')

    print(new_env)
    print("")
    print(ctx.env)
