#! /usr/bin/env python

top = '.'
out = 'build'

def configure(ctx):
	ctx.env['CCFLAGS'] = ['-g']
	ctx.env.CCFLAGS = ['-g']
	ctx.env.append_value('CXXFLAGS', ['-O2', '-g'])
	ctx.env.append_unique('CCFLAGS', ['-g', '-O2'])
	ctx.env.prepend_value('CCFLAGS', ['-O3'])

	print(type(ctx.env))
	print(ctx.env)
	print(ctx.env.FOO)

