#! /usr/bin/env python

top = '.'
out = 'build'

def configure(ctx):
	ctx.check_tool('g++')
	ctx.check_tool('src2cpp', tooldir='.')

def build(ctx):
	ctx.program(
		source = 'comp.cpp',
		target = 'comp')

	ctx.add_group()

	ctx.program(
		source = 'main.cpp a.src',
		target = 'foo')

