fontbase = '../../script-test/fonts/thai/'

for ext in ('', '-Bold') :
    font(target = 'Norasi' + ext + '.ttf',
         source = process(fontbase + 'font-source/Norasi' + ext + '.sfd', cmd("../"+fontbase+"../../bin/rmOverlap ${DEP} ${TGT}")))
