#!/usr/bin/python
# this is a smith configuration file 

# set the default output folders
out="results"
DOCDIR="documentation"
OUTDIR="installers"
ZIPDIR="releases"

APPNAME = 'loma'
VERSION = '0.0.1'
fontbase = '../../script-test/fonts/thai/'

for ext in ('', '-Bold') :
    font(target = 'Loma' + ext + '.ttf',
         source = fontbase + 'font-source/Loma' + ext + '.sfd')
