#! /usr/bin/env python

top = '.'
out = 'build'

def configure(ctx):
    print('→ configuring the project in ' + ctx.path.abspath())

def ping(ctx):
    print('→ ping from ' + ctx.path.abspath())
    ctx.recurse('src')
