#!/usr/bin/python
# this is a smith configuration file 

# set the default output folders
out="results"
DOCDIR="documentation"
OUTDIR="installers"
ZIPDIR="releases"


APPNAME="a2btest"
VERSION=0.1

kbd (source = 'demo-a2b.kmn',
     kmx = 'demo-a2b.kmx',
     mskbd = mskbd()
    )
       
