#! /usr/bin/env python

top = '.'
out = 'bin'

def configure(conf):
	pass

def build(bld):
	tg = bld(source='test.pc.in', VERSION='1.1', LIBS='moo', XPM_LIBS='-lxpm', LIBICONV='-liconv', XPM_CFLAGS='-O3')


