#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006-2010 (ita)

# the following two variables are used by the target "waf dist"
VERSION='0.0.1'
APPNAME='cxx_test'

# these variables are mandatory ('/' are converted automatically)
top = '.'
out = 'build'

from waflib.Build import BuildContext

def options(opt):
	opt.load('compiler_cxx')

def configure(conf):
	conf.load('compiler_cxx')

	bld = BuildContext(top_dir=conf.srcnode.abspath(), out_dir=conf.bldnode.abspath())
	bld.all_envs['default'] = conf.env
	bld.init_dirs()
	bld.logger = make_logger('test1', conf.logger)
	bld.check(header_name='stdio.h', features='cxx cxxprogram', mandatory=False)
	bld.logger.memhandler.flush()

def build(bld):
	pass

import logging
from logging.handlers import MemoryHandler
def make_logger(name, to_log):
	logger = logging.getLogger(name)
	hdlr = MemoryHandler(10000, target=to_log)
	formatter = logging.Formatter('%(message)s')
	hdlr.setFormatter(formatter)
	logger.addHandler(hdlr)
	logger.memhandler = hdlr
	logger.setLevel(logging.DEBUG)
	return logger

