#! /usr/bin/env python
# encoding: utf-8


def fun(task):
	#print task.generator.bld.name_to_obj('somelib').link_task.outputs[0].abspath(task.env)
	task.ut_exec.append('--help')

bld(
	features = 'cxx cxxprogram test',
	source   = 'AccumulatorTest.cpp',
	target   = 'unit_test_program',
	uselib   = 'CPPUNIT',
	uselib_local = 'unittestmain useless',
	ut_cwd   = bld.path.abspath(),
	ut_fun   = fun
)

