#! /usr/bin/env python

import sys

def options(opt):
	opt.pimp('compiler_c')

def configure(conf):
	conf.check_tool('compiler_c')

	conf.env.INCLUDES_TEST = ['/usr/include']

	if sys.platform != 'win32':
		conf.env.DEFINES_TEST    = ['TEST']
		conf.env.CCFLAGS_TEST    = ['-O0']
		conf.env.LIB_TEST        = ['m']
		conf.env.LIBPATH_TEST    = ['/usr/lib']
		conf.env.LINKFLAGS_TEST  = ['-g']
		conf.env.INCLUDES_TEST   = ['/opt/gnome/include']

def build(bld):
	mylib = bld.stlib(
		source   = 'test_staticlib.c',
		target   = 'teststaticlib',
		use      = 'TEST')

	if mylib.env.CC_NAME == 'gcc':
		mylib.cxxflags = ['-O2']

