#! /usr/bin/env python

def options(opt):
	opt.imp('compiler_c')

def configure(conf):
	conf.imp('compiler_c')

def build(bld):
	bld.program(source='main.c', target='app', use='myshlib mystlib')
	bld.stlib(source='a.c', target='mystlib')
	bld.shlib(source='b.c', target='myshlib', use='myobjects')
	bld.objects(source='c.c', target='myobjects')

