#! /usr/bin/env python

bld.shlib(
	#packages = 'gtk+-2.0',
	features = 'c cshlib',
	target   = 'hello-world',
	#uselib   = 'GTK GLIB',
	source   = bld.path.ant_glob('src/*.vala'),
	gir      = 'hello-1.0'
	)

