#! /usr/bin/env python

def build(bld):

	bld(features  = 'javac jar',
		name      = 'animals',

		# javac
		srcdir    = 'src',
		compat    = '1.5',
		# jar
		basedir   = 'src',
		destfile  = 'animals.jar',
	)

