#! /usr/bin/env python

def build(bld):

	t = bld(
		features  = 'javac jar',
		name      = 'animals',

		# javac
		srcdir    = 'src',
		compat    = '1.5',

		# jar
		basedir   = 'src',
		destfile  = 'animals.jar',
	)

	if bld.env.DO_JUNIT:
		bld(
			features  = 'javac junit',
			srcdir    = 'junit',
			compat    = '1.5',

			junitsrc  = 'junit',
			junitclasspath = '.',
			uselib    = 'JUNIT',
			use       = 'animals'
		)

