#! /usr/bin/env python

def build(bld):

    bld(features  = 'javac',
        srcdir    = 'src',
        compat    = '1.5',
        name      = 'animals-src',
    )

    bld(features  = 'jar',
        basedir   = 'src',
        destfile  = 'animals.jar',
        use       = 'animals-src',
        name      = 'animals'
    )

