#!/bin/bash

function usage() {
    cat <<EOT
usage: rrun [ options ] cmd [args]

runs the command (with its args) by first rsyncing the current directory 
to a ramdisk (/dev/shm), running the cmd, and then rsyncing everything back.

Any options supplied are passed on to both calls to rsync, and can be any of:
        -v          increase verbosity; also displays ramdisk location
        -c          skip based on checksum, not mod-time & size
        -n          perform a trial run with no changes made
        -C          auto-ignore files in the same way CVS does
        -f RULE     add a file-filtering RULE
        -F          same as: -f 'dir-merge /.rsync-filter'
                    repeated: -f '- .rsync-filter'
        -i          output a change-summary for all updates

See rsync manpage for more information about these options.

EOT
}

CACHE_ID=$(md5sum <<< "$PWD" | cut -d ' ' -f1)
CDIR="/dev/shm/rrun/$CACHE_ID"

# Accumulate specific options from command line to pass to rsync:
declare -a rsyncOpts
while getopts "f:vcnCFi" flag; do
  case $flag in
    f)
       rsyncOpts+=("-$flag" "$OPTARG")
       ;;
    [cnCFi])
       rsyncOpts+=("-$flag")
       ;;
    v)
       rsyncOpts+=("-$flag")
       echo "ramdisk location: ${CDIR}"
       ;;
    *)
       usage
       exit 1
       ;;
  esac
done

# Remaining parameters constitute the command string to be executed:
shift $((OPTIND-1))

# Issue usage message if nothing to do:
if [ $# -eq 0 ]; then
    usage
    exit 1
fi

# Process the command string for forwarding to bash inside the here doc by
# printing each parameter in quoted form and stripping of the escaping for
# isolated common shell meta-characters:
quoted=$(echo "${@@Q}" | sed -r "s/ '([;()|&]+)' / \1 /g")

# for debugging parameter parsing:
# echo ${rsyncOpts[@]@Q} ${quoted}

# Sync current directory into the cache dir:
mkdir -p $CDIR;
rsync -am "${rsyncOpts[@]}" --del ./ "$CDIR/"

# Run the command inside a user and mount namespaces, so we can bind-mount
# the cachedir over the target dir:
unshare -rm /bin/bash << EOT
mount --bind "$CDIR" .
cd "$PWD"
# The following is used instead of "$@" which acts like "$*" in this context
${quoted}
EOT

# Sync results back
rsync -amu "${rsyncOpts[@]}" --del "$CDIR/" ./
