#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2008-2010 (ita)

top = '.'
out = 'build'

def configure(conf):
	conf.load('gcc')
	conf.load('mytool', tooldir='.')

def build(bld):
	bld.env.COMP = bld.path.find_resource('evil_comp.py').abspath()
	bld.stlib(source='x.c foo.src', target='astaticlib')

