# -*- mode: ruby -*-
# vi: set ft=ruby :
# Vagrant file config to get the latest smith and its dependencies 
# put this in your project folder along with the provision.sh file referenced below.
# last tested to work with vagrant version 2.2.1 and Virtualbox 5.2.14

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "ubuntu/bionic64"

  # we turn off the box update warning.
  # vagrant up will still do the check/warn.
  config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which is generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder ".", "/smith", type: "virtualbox"
  
  # If you want you can also map the parent folder of all your local font working copies:
  # for macOS users:
  # config.vm.synced_folder "/Users/username/work/fonts/", "/smith", type: "virtualbox"
  # for Ubuntu users:
  # config.vm.synced_folder "/home/username/work/fonts/", "/smith", type: "virtualbox"

  # set up a distinguishable hostname
  config.vm.hostname = "smith-bionic"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
    vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]

    # Do not display the VirtualBox GUI when booting the machine
    vb.gui = false 

    # Customize the amount of memory on the VM:
    vb.memory = "4096"

    # Customize the amount of CPUs allocated:
    vb.cpus = 4

  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL

    # uncomment if you need to tweak colours 
    # export VAGRANT_NO_COLOR="true"
    
    # turning off some automated apt-related stuff 
    sudo systemctl stop apt-daily.service # disable run when system boot
    sudo systemctl disable apt-daily.service # disable run when system boot
    sudo systemctl stop apt-daily.timer   # disable timer run 
    sudo systemctl disable apt-daily.timer   # disable timer run 

    sleep 5 

    lsb_release -d

    sudo dpkg-reconfigure locales -f noninteractive -p critical

    sudo apt-get update -q -y

    sudo apt-get install --no-install-recommends -q -y less vim-nox htop tree git mercurial subversion pydf wget curl bash-completion software-properties-common

    SHELL

    config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  # install and configure the smith-specific components
    config.vm.provision :shell, :path => "provision.sh"

end
