#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2010 (ita)

VERSION='0.0.1'
APPNAME='cpp_gen'

top = '.'
out = 'build'

def options(opt):
	opt.load('compiler_cxx')

def configure(conf):
	conf.load('compiler_cxx')
	conf.check(header_name='stdio.h', features='cxx cxxprogram', mandatory=False)

def build(bld):
	bld(features='cxx cxxprogram copya', source='main.cpp a.cpp', target='app')

#--------

from waflib import Task, TaskGen
from waflib.Tools import cxx

@TaskGen.feature('copya')
@TaskGen.after('process_source')
def copya_create_task(self):
	for x in self.tasks:
		if x.inputs and x.inputs[0].name == 'a.cpp' and x.__class__.__name__ != 'copy':
			node = x.inputs[0]
			copy_tsk = self.create_task('copy', node, node.change_ext('.cpp.cpp'))
			cxx_tsk = cxx.cxx_hook(self, copy_tsk.outputs[0])
			cxx_tsk.set_run_after(copy_tsk) # recommended

class copy(Task.Task):
	run_str = 'cp ${SRC} ${TGT}'

