#! /usr/bin/env python

"""
waf configure clean build -j4 --dwidth=800
"""

def options(ctx):
	ctx.tool_options('parallel_debug')

def configure(ctx):
	ctx.check_tool('parallel_debug')

def build(ctx):
	for i in range(8):
		ctx(rule='cp ${SRC} ${TGT}', source='wscript', target='wscript_a_%d' % i, color='GREEN')
		ctx(rule='cp ${SRC} ${TGT}', source='wscript_a_%d' % i, target='wscript_b_%d' % i, color='YELLOW')
	ctx.add_group()
	for i in range(8):
		ctx(rule='cp ${SRC} ${TGT}', source='wscript', target='wscript_c_%d' % i, color='BLUE')
		ctx(rule='cp ${SRC} ${TGT}', source='wscript_c_%d' % i, target='wscript_d_%d' % i, color='PINK')
