#!/usr/bin/python
# this is a smith configuration file 

# set the default output folders
out="results"
DOCDIR="documentation"
OUTDIR="installers"
ZIPDIR="releases"

prjbase = '../../script-test/'
fontbase = prjbase + 'fonts/thai/font-source/'
basebin = prjbase + 'bin'

APPNAME = 'loma-minority'
VERSION = '0.0.1'
TESTDIR = prjbase + 'fonts/thai/tests'
TESTRESULTSDIR = 'tests'
DESC_SHORT = "Loma with minority extensions"
DESC_LONG = """Loma with minority extensions
These fonts support extra characters and sequences as needed for
minority languages that use the Thai script. Specifically this
font supports the following language needs: Patani Malay, So"""
LICENSE = "GPL.txt"

t = fonttest(targets = {
    'pdfs' : tex(),
    'test' : tests(),
    'report' : tests({'report' : cmd("${FONTREPORT} ${SRC[0]} > ${TGT}")}, coverage = "fonts")
    })

for ext in ('', '-Bold') :
    fbase = 'Loma' + ext
    font(target = process(fbase + '-Minority.ttf', name("Loma Minority")),
         source = process(fontbase + fbase + '.sfd', cmd('${RMOVERLAP} ${DEP} ${TGT}')),
         version = 0.1,
         woff = woff(),
         opentype = internal(),
         graphite = gdl(fbase + '.gdl', master = fontbase + 'master.gdl'),
         ap = fbase + '.xml',
         script = 'thai',
         fret = fret(params = '-r'),
         tests = t
        )

def configure(conf) :
    import os
    basepath = os.environ['PATH'].split(os.pathsep) + [os.path.abspath(basebin)]
    conf.find_program('rmOverlap', path_list = basepath)
    try :
        conf.find_program('fontreport', path_list = basepath)
    except conf.errors.ConfigurationError :
        pass
