#! /usr/bin/env python

top = '.'
out = 'build'

def options(ctx):
    ctx.add_option('--foo', action='store', default=False, help='Silly test')

def configure(ctx):
    from waflib import Options
    ctx.env.FOO = Options.options.foo
    ctx.find_program('touch', var='TOUCH', mandatory=True) # a configuration helper

def build(ctx):
    print(ctx.env.TOUCH)
    print(ctx.env.FOO)
    ctx(rule='${TOUCH} ${TGT}', target='bar.txt')

