name: build docs

on:
  push:
    branches:
    - master

jobs:
  doc_build:
    runs-on: ubuntu-latest
    name: building
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Get env set up
      run: |
          sudo apt-get update
          sudo apt-get install asciidoctor ruby-pygments.rb ruby-rouge -y
          asciidoctor -t -v -D docs/smith --backend=xhtml5 -n -a toc=left -a source-hightlighter=rouge -o index.html docs/smith/manual.adoc
    - name: Deploy docs to gh-pages
      uses: peaceiris/actions-gh-pages@v4
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs/smith

