name: build docs

on:
  push:
    branches:
    - master

jobs:
  doc_build:
    runs-on: ubuntu-latest
    name: building
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Get build container
      id: adocbuild
      uses: tonynv/asciidoctor-action@master
          run: |
              sudo apt-get update
              sudo apt-get -y ruby-pygments.rb
      with:
          program: "asciidoctor -t -v -D docs/smith --backend=xhtml5 -n -a toc=left -a source-hightlighter-pygments -o index.html docs/smith/manual.adoc"
    - name: Print execution time
      run: echo "Time ${{ steps.adocbuild.outputs.time }}"
    - name: Deploy docs to gh-pages
      uses: peaceiris/actions-gh-pages@v4
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs/smith

