name: Prune images
on:
  registry_package:
    types: [published]

jobs:
  prune:
    runs-on: ubuntu-latest
    steps:
    - name: prune interactive images
      uses: vlaurin/action-ghcr-prune@v0.5.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        organization: silnrsi
        container: smith
        dry-run: true
        keep-younger-than: 15
        keep-last: 14
        prune-tags-regexes: ^.*$
        prune-untagged: true
