name: Prune images
on:
  registry_package:
    types: [published]
  workflow_dispatch: 
    inputs:
      dryrun:
        type: boolean
        default: true

jobs:
  prune:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: snok/container-retention-policy@v3.0.0
      with:
        account: silnrsi
        token: ${{ secrets.GITHUB_TOKEN }}
        image-names: ${{ github.event.repository.name }}
        tag-selection: tagged
        cut-off: 2w
        keep-n-most-recent: 14
        dry-run: ${{ inputs.dryrun }}
