#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2008 (ita)

VERSION='0.0.2'
APPNAME='gcj_test'

top = '.'
out = 'out'

def configure(conf):
	conf.check_tool('gcj', tooldir='.')

def build(bld):
	bld(
		features     = 'gcj',
		java_source  = '.*java$',
		source_root  = 'src',
		target       = 'test',
		gcjlinkflags = '--main=es.Hello',
		gcjonce      = True)

